name = "worker"
main = "src/index.ts"
compatibility_date = "2023-12-01"
account_id = "d001056151c5f5088cb383308987d0b1"

[vars]
SUPABASE_URL = "https://kvmqydhrmdynyyaiojfs.supabase.co"

[[queues.consumers]]
queue = "jobs"
max_batch_size = 10
max_batch_timeout = 30
