name = "api"
main = "src/index.ts"
compatibility_date = "2023-12-01"
account_id = "d001056151c5f5088cb383308987d0b1"

[vars]
SUPABASE_URL = "https://placeholder.supabase.co"

[[queues.producers]]
queue = "jobs"
binding = "JOB_QUEUE"
